# shellcheck shell=bash
# Shared helpers for the local reporting runtime scripts.
set -euo pipefail

LRR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export LRR_DIR
cd "$LRR_DIR"

[[ -f .env ]] && set -a && source .env && set +a
export LRR_PFX_PASSWORD="${LRR_PFX_PASSWORD:-lrr-dev-only}"
export LRR_MOCKPORTEN_PASSWORD="${LRR_MOCKPORTEN_PASSWORD:-lrr-synthetic-only}"
# Synthetic Maskinporten machine client for the app (generated by gen-certs.sh)
if [[ -f certs/maskinporten-client.jwk.b64 ]]; then
  export LRR_MASKINPORTEN_JWK_B64="$(<certs/maskinporten-client.jwk.b64)"
  export LRR_MASKINPORTEN_PUBLIC_JWK="$(<certs/maskinporten-client.public.jwk.json)"
fi
export APP_URL="https://app.local.altinn.cloud/ttd/frontend-test"

GATEWAY_URL="https://local.altinn.cloud"
CA_CERT="$LRR_DIR/certs/ca.crt"
AZURITE_KEY="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
AZURITE_CONN="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=${AZURITE_KEY};BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"

# Synthetic test identities (Tenor-style: month digit +80). Never real people.
AUTHORIZED_PID="02856221086"      # DAGL for the reporting org -> allowed
UNAUTHORIZED_PID="15877749964"    # no roles -> denied
REPORTING_ORGNO="310548510"       # synthetic org number (Mod11 valid)

log()  { printf '\033[1;34m[lrr]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[1;31m[lrr] %s\033[0m\n' "$*" >&2; exit 1; }

curl_gw() { curl -sS --cacert "$CA_CERT" "$@"; }

psql_lrr() { docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U postgres "$@"; }

wait_for() { # wait_for <description> <seconds> <cmd...>
  local desc="$1" secs="$2"; shift 2
  local i=0
  until "$@" >/dev/null 2>&1; do
    ((i++ >= secs)) && fail "timeout waiting for $desc"
    sleep 1
  done
  log "ready: $desc"
}
